---
# file: roles/common/tasks/hosts.yml

  - name: remove existing entries of all hosts in {{ hostsfile }}
    lineinfile:
      dest: '{{ hostsfile }}'
      regexp: '\b{{ item }}\b'
      state: absent
    when: hostvars[item].ansible_ssh_host is defined
    with_items: "{{ groups.all }}"
    become: yes

  - name: add all hosts to {{ hostsfile }}
    lineinfile:
      dest: '{{ hostsfile }}'
      regexp: '\b{{ item }}\b'
      line: "{{ hostvars[item].ansible_ssh_host }} {{ item }}.{{ subdomain }} {{ item }}"
      state: present
    when: hostvars[item].ansible_ssh_host is defined
    with_items: "{{ groups.all }}"
    become: yes

  - name: add addional alliases to {{ hostsfile }}
    lineinfile:
      dest: '{{ hostsfile }}'
      regexp: '^(.*{{ item }}\w*)$'
      line: '\1 {{ hostvars[item].additional_dns_aliases }}'
      backrefs: yes
    when: hostvars[item].additional_dns_aliases is defined
    with_items: "{{ groups.all }}"
    become: yes

  - name: remove existing entries of all additional hosts in {{ hostsfile }}
    lineinfile:
      dest: '{{ hostsfile }}'
      regexp: '\b{{ item.key }}\b'
      state: absent
    loop: "{{ lookup('dict', additional_hosts|default({}), wantlist=True) }}"
    become: yes

  - name: add additional hosts to {{ hostsfile }}
    lineinfile:
      dest: '{{ hostsfile }}'
      regexp: '\b{{ item.key }}\b'
      line: "{{ item.value.additional_hosts_ip }} {{ item.key }}.{{ subdomain }} {{ item.key }}"
      state: present
    loop: "{{ lookup('dict', additional_hosts|default({}), wantlist=True) }}"
    become: yes

  - name: add additional hosts aliases to {{ hostsfile }}
    lineinfile:
      dest: '{{ hostsfile }}'
      regexp: '^(.*\s{{ item.key }})\s*$'
      line: '\1 {{ item.value.additional_host_dns_aliases }}'
      backrefs: yes
    loop: "{{ lookup('dict', additional_hosts|default({}), wantlist=True) }}"
    become: yes
